---
# Particle setup values:
random_inputs: True # No such functionality for this being false...
random_seed  : 'BestOne'
max_mass     : 1000
max_distance : 100
max_speed    : 5

# Simulation constants:
G : 10 #0.005
dt : 0.01 #s
number_of_particles : 10
collision_distance : 1
timesteps : 2000 #s

# Plot constants:
total_plot_points : 1000

Logging info:
  format : '%(asctime)s [%(levelname)s] %(module)s > %(funcName)s: %(message)s'
  level : logging.INFO
  datefmt : '%I:%M:%S'

...